### PR TITLE
Create CI Pipeline

### PR DESCRIPTION
**Pull request by luigieai**
Hello, based on https://github.com/nitin-787/mynotes/issues/68, this adds a workflow for testing the project at every push to main branch, as the issue doesnt go in depth of what this project needs about workflows, we have a success condition based at project's own written tests.

### CODE REVIEW

**Comment by nitin-787** [comment]
> Hello, based on https://github.com/nitin-787/mynotes/issues/68, this adds a workflow for testing the project at every push to main branch, as the issue doesnt go in depth of what this project needs about workflows, we have a success condition based at project's own written tests. 
> 

Yes I know but the person who the made the pull request at least he should make sure the initial c/cd pipeline works, he just copied the code from some and made pull request

**Comment by nitin-787** [comment]
> > Hello, based on https://github.com/nitin-787/mynotes/issues/68, this adds a workflow for testing the project at every push to main branch, as the issue doesnt go in depth of what this project needs about workflows, we have a success condition based at project's own written tests. 
> > 
> 
> Yes I know but the person who the made the pull request at least he should make sure the initial c/cd pipeline works, he just copied the code from some and made pull request along with that he said he don't have knowledge of flutter and ci/cd pipeline but still I helped him

**Comment by luigieai** [comment]
@nitin-787 Sure, i'm not aiming at anything, just trying to explain what the pipelines achieves :) Take a look and we can work further if needed.

**Comment by nitin-787** [comment]
> @nitin-787 Sure, i'm not aiming at anything, just trying to explain what the pipelines achieves :) Take a look and we can work further if needed.

Thanks, but I know lil but about ci/cd pipeline

**Pull request merged**
