### PR TITLE
issue Resolved for dounloading button added 

### PR DESCRIPTION
**Pull request by piyushkumar12111111**
Resolved the Problem of Dounloading the Notes file

### CODE REVIEW

**Comment by piyushkumar12111111** [comment]
Added the Download Button

**Review by nitin-787 — CHANGES_REQUESTED** [review]
### Hey it looks like you deleted some important files

**Comment by piyushkumar12111111** [comment]
NO sir i have not deleted anything

**Comment by nitin-787** [comment]
> NO sir i have not deleted anything

can you contact me again? I'll tell you what is the issue

**Pull request closed without merging**
